/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Spud2astroRouteImport } from './routes/spud2astro'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SocialRouteImport } from './routes/social'
import { Route as MvxRouteImport } from './routes/mvx'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIndexRouteImport } from './routes/teams.index'
import { Route as TeamsRocketLeagueRouteImport } from './routes/teams.rocket-league'
import { Route as TeamsRainbowSixSiegeRouteImport } from './routes/teams.rainbow-six-siege'
import { Route as TeamsFortniteRouteImport } from './routes/teams.fortnite'
import { Route as CoachesRajtkoRouteImport } from './routes/coaches.rajtko'

const Spud2astroRoute = Spud2astroRouteImport.update({
  id: '/spud2astro',
  path: '/spud2astro',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const MvxRoute = MvxRouteImport.update({
  id: '/mvx',
  path: '/mvx',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRocketLeagueRoute = TeamsRocketLeagueRouteImport.update({
  id: '/teams/rocket-league',
  path: '/teams/rocket-league',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRainbowSixSiegeRoute = TeamsRainbowSixSiegeRouteImport.update({
  id: '/teams/rainbow-six-siege',
  path: '/teams/rainbow-six-siege',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsFortniteRoute = TeamsFortniteRouteImport.update({
  id: '/teams/fortnite',
  path: '/teams/fortnite',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRajtkoRoute = CoachesRajtkoRouteImport.update({
  id: '/coaches/rajtko',
  path: '/coaches/rajtko',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/mvx': typeof MvxRoute
  '/social': typeof SocialRoute
  '/sponsors': typeof SponsorsRoute
  '/spud2astro': typeof Spud2astroRoute
  '/coaches/rajtko': typeof CoachesRajtkoRoute
  '/teams/fortnite': typeof TeamsFortniteRoute
  '/teams/rainbow-six-siege': typeof TeamsRainbowSixSiegeRoute
  '/teams/rocket-league': typeof TeamsRocketLeagueRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/mvx': typeof MvxRoute
  '/social': typeof SocialRoute
  '/sponsors': typeof SponsorsRoute
  '/spud2astro': typeof Spud2astroRoute
  '/coaches/rajtko': typeof CoachesRajtkoRoute
  '/teams/fortnite': typeof TeamsFortniteRoute
  '/teams/rainbow-six-siege': typeof TeamsRainbowSixSiegeRoute
  '/teams/rocket-league': typeof TeamsRocketLeagueRoute
  '/teams': typeof TeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/mvx': typeof MvxRoute
  '/social': typeof SocialRoute
  '/sponsors': typeof SponsorsRoute
  '/spud2astro': typeof Spud2astroRoute
  '/coaches/rajtko': typeof CoachesRajtkoRoute
  '/teams/fortnite': typeof TeamsFortniteRoute
  '/teams/rainbow-six-siege': typeof TeamsRainbowSixSiegeRoute
  '/teams/rocket-league': typeof TeamsRocketLeagueRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/mvx'
    | '/social'
    | '/sponsors'
    | '/spud2astro'
    | '/coaches/rajtko'
    | '/teams/fortnite'
    | '/teams/rainbow-six-siege'
    | '/teams/rocket-league'
    | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/mvx'
    | '/social'
    | '/sponsors'
    | '/spud2astro'
    | '/coaches/rajtko'
    | '/teams/fortnite'
    | '/teams/rainbow-six-siege'
    | '/teams/rocket-league'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/mvx'
    | '/social'
    | '/sponsors'
    | '/spud2astro'
    | '/coaches/rajtko'
    | '/teams/fortnite'
    | '/teams/rainbow-six-siege'
    | '/teams/rocket-league'
    | '/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  MvxRoute: typeof MvxRoute
  SocialRoute: typeof SocialRoute
  SponsorsRoute: typeof SponsorsRoute
  Spud2astroRoute: typeof Spud2astroRoute
  CoachesRajtkoRoute: typeof CoachesRajtkoRoute
  TeamsFortniteRoute: typeof TeamsFortniteRoute
  TeamsRainbowSixSiegeRoute: typeof TeamsRainbowSixSiegeRoute
  TeamsRocketLeagueRoute: typeof TeamsRocketLeagueRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spud2astro': {
      id: '/spud2astro'
      path: '/spud2astro'
      fullPath: '/spud2astro'
      preLoaderRoute: typeof Spud2astroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mvx': {
      id: '/mvx'
      path: '/mvx'
      fullPath: '/mvx'
      preLoaderRoute: typeof MvxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/rocket-league': {
      id: '/teams/rocket-league'
      path: '/teams/rocket-league'
      fullPath: '/teams/rocket-league'
      preLoaderRoute: typeof TeamsRocketLeagueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/rainbow-six-siege': {
      id: '/teams/rainbow-six-siege'
      path: '/teams/rainbow-six-siege'
      fullPath: '/teams/rainbow-six-siege'
      preLoaderRoute: typeof TeamsRainbowSixSiegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/fortnite': {
      id: '/teams/fortnite'
      path: '/teams/fortnite'
      fullPath: '/teams/fortnite'
      preLoaderRoute: typeof TeamsFortniteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches/rajtko': {
      id: '/coaches/rajtko'
      path: '/coaches/rajtko'
      fullPath: '/coaches/rajtko'
      preLoaderRoute: typeof CoachesRajtkoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  MvxRoute: MvxRoute,
  SocialRoute: SocialRoute,
  SponsorsRoute: SponsorsRoute,
  Spud2astroRoute: Spud2astroRoute,
  CoachesRajtkoRoute: CoachesRajtkoRoute,
  TeamsFortniteRoute: TeamsFortniteRoute,
  TeamsRainbowSixSiegeRoute: TeamsRainbowSixSiegeRoute,
  TeamsRocketLeagueRoute: TeamsRocketLeagueRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
